# -*- coding: utf-8 -*-
"""メディア工学課題1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9kecwayTqGLZxjcj9ozhMC5eNS_PYz8
"""

#問題1-1 １から入力された自然数までの各ヶの２乗を合計するプログラムを作成しろ。
#NΣk^2 k=1
#これは入力された自然数をNとしてfor文で1からのNまでのそれぞれの２乗を合計値に足していく考え方で行った

num=int(input('１からの自然数を入力してください>>  ')) #入力された数字は初めは文字列型のためint型に変えて変数numに代入
sum=0 #合計値を出力させる変数sumを初期化
for i in range(1,num+1): #1から入力された数字までを繰り返す 
  sum+=i**2 #それぞれの数字を２乗させてsumに足していく
print(sum) #数値の合計を表示

